game_name: KuhnPoker
algo_name: DeepDCFRPlus

num_episodes: 12000000
advantage_buffer_size: 1000000
ave_policy_buffer_size: 1000000
learning_rate: 1.0e-3
num_traversals: 10000
advantage_network_train_steps: 750
ave_policy_network_train_steps: 5000
ave_policy_batch_size: 2048
advantage_batch_size: 2048
reinitialize_advantage_networks: False
use_regret_matching_argmax: True
num_layers: 3
num_hiddens: 64
evaluation_frequency: 3
epsilon: 0.6
alpha: 2
gamma: 2

save_log: True
device: cpu
